#!/bin/sh
#-------------------------------------------------------------------------------
#
# Setup script for low-level Spinnaker work
#
#-------------------------------------------------------------------------------

# Copyright (c) 2015-2023 The University of Manchester
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -a

#-------------------------------------------------------------------------------

# This file should be sourced, not executed!
if [ "$0" == "${BASH_SOURCE[0]}" ]; then
  echo "WARNING: $0 should be sourced, not executed. Try: source $0"
fi

#-------------------------------------------------------------------------------

# SPINN_DIRS should point to the directory containing subdirs "tools",
# "lib", "include", etc. It's used by many tools to locate resources.
# used during the building of SpiNNaker applications. The subdirectory
# "tools" contains locally developed tools for building applications.

SPINN_DIRS=`cd "$(dirname "${BASH_SOURCE[0]}")";pwd -P`

#-------------------------------------------------------------------------------

# SPINN_PATH is a path variable (elements separated by ":"). It's used
# to find resources used while building and running applications. It
# should always contain at least the "tools/boot" directory of $SPINN_DIRS

SPINN_PATH=$SPINN_DIRS/tools/boot

#-------------------------------------------------------------------------------

# Add the "tools" directory to the Unix PATH and to the Perl library
# search path.

PATH=$SPINN_DIRS/tools:$PATH

PERL5LIB=$SPINN_DIRS/tools:$PERL5LIB

#-------------------------------------------------------------------------------

# Set up variables pointing to the ARM software development tools
# These tools need a licence file so set that up as well. You may need
# to edit this section for your local environment

# *** EDIT HERE ***

ARMTOOLS=/home/amulinks/spinnaker/tools/RVDS40

ARMBIN=$ARMTOOLS/RVCT/Programs/4.0/400/linux-pentium
ARMLIB=$ARMTOOLS/RVCT/Data/4.0/400/lib
ARMINC=$ARMTOOLS/RVCT/Data/4.0/400/include/unix

LM_LICENSE_FILE=PORT@SERVER.cs.man.ac.uk:$LM_LICENSE_FILE

#-------------------------------------------------------------------------------

# Set up variables pointing to the GNU software development tools.
# You may need to edit this section for your local environment

# *** EDIT HERE ***

GNUTOOLS=/local/temples/gcc-arm-none-eabi-4_9-2015q3

GNUBIN=$GNUTOOLS/bin

#-------------------------------------------------------------------------------

# Finally, add ARM and GNU software development tools to the PATH

PATH=$GNUBIN:$ARMBIN:$PATH

#-------------------------------------------------------------------------------


chmod u+x $SPINN_DIRS/tools/*

