#!/usr/bin/perl

# Copyright (c) 2017-2019 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict;
use warnings;

die "bad args\n" unless $#ARGV == 1 && -r $ARGV[0] && $ARGV[1] =~ /^\d+$/;

my ($file, $size) = @ARGV;

my $file_size = -s $file;
my $buf;

die "file of $file_size bytes too big for $size\n" if $file_size > $size;

open my $fh, "<", $file or die "Can't open $file\n";
binmode($fh);
my $r = sysread $fh, $buf, $file_size;
close $fh;

die "failed to read file\n" if $r != $file_size;

my $pad = chr (0) x ($size - $file_size);

binmode(STDOUT);
print $buf, $pad;
