#!/usr/bin/perl

# Copyright (c) 2015 The University of Manchester
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

use strict;
use warnings;

die "bad args\n" unless $#ARGV == 1 && -r $ARGV[0] && $ARGV[1] =~ /^\d+$/;

my ($file, $size) = @ARGV;

my $file_size = -s $file;
my $buf;

die "file too big\n" if $file_size > $size;

open my $fh, "<", $file or die "Can't open $file\n";
binmode($fh);
my $r = sysread $fh, $buf, $file_size;
close $fh;

die "failed to read file\n" if $r != $file_size;

my $pad = chr (0) x ($size - $file_size);

binmode(STDOUT);
print $buf, $pad;
