#!/usr/bin/perl

# Utility to substitute build date and software version in a file
#
#  - string BUILD_DATE replaced by Unix time
#  - string SW_VER_NUM replaced by number derived from $SPINN_STV
#  - string SW_VER_STR replaced by "$SPINN_STV"


my $stv = $ENV{SPINN_STV};

die "bad args" unless $#ARGV == 0;
die "SPINN_STV not defined" unless $stv;
die "SPINN_STV badly formatted" unless  $stv =~ /^(\d+)\.(\d+)\.(\d+)(-\w+)?$/;

my ($x, $y, $z, $tag) = ($1, $2, $3, $4);

$tag ||= "";

for my $v ($x, $y, $z)
{
    die "Version out of range ($v)" if $v < 0 || $v > 255;
}

my $build_date = sprintf "%d", time ();
my $sw_ver_num = sprintf "0x%08x", ($x << 16) + ($y << 8) + $z;
my $sw_ver_str = sprintf "\"%s\"", $stv;

while (<>)
{
    s/BUILD_DATE/$build_date/;
    s/SW_VER_NUM/$sw_ver_num/;
    s/SW_VER_STR/$sw_ver_str/;
    print;
}
