#!/usr/bin/perl

# Copyright (c) 2015 The University of Manchester
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Utility to create a small C file (on stdout) which contains
#
#  - an integer constant which is the Unix time.
#  - a string constant containing the first 15 characters of the argument

die "bad args" unless $#ARGV == 0;

my $name = substr $ARGV[0], 0, 15;

printf "const int  build_date   = %d;\n", time ();
printf "const char build_name\[\] = \"%s\";\n", $name;
