#!/usr/bin/perl

# Copyright (c) 2017-2019 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Utility to create a small C file (on stdout) which contains
#
#  - an integer constant which is the Unix time.
#  - a string constant containing the first 15 characters of the argument

die "bad args" unless $#ARGV == 0;

my $name = substr $ARGV[0], 0, 15;

printf "const int  build_date   = %d;\n", time ();
printf "const char build_name\[\] = \"%s\";\n", $name;
