# Copyright (c) 2020 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This workflow will install Python dependencies, run tests, lint and rat with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: C Actions
on: [push]
jobs:
  build:
    # Checks that need a compiler
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install system dependencies
      run: sudo apt-get -q install gcc-arm-none-eabi freeglut3-dev --fix-missing
    - name: Set C environment variables
      run: |
        echo "SPINN_DIRS=$PWD" >> $GITHUB_ENV
        echo "SPINN_PATH=$PWD/tools/boot" >> $GITHUB_ENV
        echo "PERL5LIB=$PWD/tools" >> $GITHUB_ENV
        echo "$PWD/tools" >> $GITHUB_PATH
    - name: Build C code
      run: |
        make
        make -C scamp
        make -C apps/hello
        make -C apps/hello_cpp
        make -C apps/life
        make -C apps/pt_demo
      env:
        GCC_COLORS: error=01;31:warning=01;35:note=01;36:range1=32:range2=34:locus=01:quote=01:fixit-insert=32:fixit-delete=31:diff-filename=01:diff-hunk=32:diff-delete=31:diff-insert=32
        CFLAGS: -fdiagnostics-color

  verify:
    # Checks that don't need to compile things
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout SupportScripts
      uses: actions/checkout@v2
      with:
        repository: SpiNNakerManchester/SupportScripts
        path: support
    - name: Set C environment variables
      run: |
        echo "SPINN_DIRS=$PWD" >> $GITHUB_ENV
        echo "SPINN_PATH=$PWD/tools/boot" >> $GITHUB_ENV
        echo "PERL5LIB=$PWD/tools" >> $GITHUB_ENV
        echo "$PWD/tools" >> $GITHUB_PATH
    - name: "Lint sark code using Vera++"
      uses: ./support/actions/vera
      with:
        base-dir: sark
    - name: "Lint scamp code using Vera++"
      uses: ./support/actions/vera
      with:
        base-dir: scamp
        profile: spinnaker-asm
    - name: "Lint spin1_api code using Vera++"
      uses: ./support/actions/vera
      with:
        base-dir: spin1_api
    - name: "Lint apps code using Vera++"
      uses: ./support/actions/vera
      with:
        base-dir: apps
        options: -P max-line-length=200
    - name: "Lint bmp code using Vera++"
      uses: ./support/actions/vera
      with:
        base-dir: bmp
        profile: spinnaker-asm
        options: -P max-line-length=200
    - name: "Lint include code using Vera++"
      uses: ./support/actions/vera
      with:
        base-dir: include
        options: -P max-line-length=200 -P max-file-length=3000
    - name: Run rat copyright enforcement
      uses: ./support/actions/check-copyrights
    - name: Build documentation using doxygen
      run: |
        sudo apt-get -q install doxygen --fix-missing
        make doxygen
